"""Add payment fields

Revision ID: 0de38857bfe6
Revises: 38c04e15b9b0
Create Date: 2025-05-28 18:56:03.389619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0de38857bfe6'
down_revision = '38c04e15b9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('appointment_ibfk_3', type_='foreignkey')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('payment_received_by')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_notes')
        batch_op.drop_column('payment_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_amount', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('payment_notes', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('payment_date', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('payment_received_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_mode', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_status', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_foreign_key('appointment_ibfk_3', 'user', ['payment_received_by'], ['id'])

    # ### end Alembic commands ###
