"""Add payment fields

Revision ID: 31a014470bc3
Revises: ef6a9dbf7d9a
Create Date: 2025-05-28 17:37:41.016163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a014470bc3'
down_revision = 'ef6a9dbf7d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('consultation_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_received_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['payment_received_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_received_by')
        batch_op.drop_column('consultation_fee')
        batch_op.drop_column('payment_amount')
        batch_op.drop_column('payment_mode')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
