"""Add payment fields

Revision ID: 38c04e15b9b0
Revises: f31c1ef42263
Create Date: 2025-05-28 18:32:44.284114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38c04e15b9b0'
down_revision = 'f31c1ef42263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_notes', sa.Text(), nullable=True))
        batch_op.drop_column('consultation_fee')
        batch_op.drop_column('payment_reference')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               nullable=True)
        batch_op.alter_column('pin_code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=6),
               existing_nullable=True)
        batch_op.alter_column('patient_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=11),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['aadhar_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('patient_number',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('pin_code',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_reference', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('consultation_fee', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('payment_notes')

    # ### end Alembic commands ###
