"""empty message

Revision ID: 3e253c65bf95
Revises: 0de38857bfe6
Create Date: 2025-06-05 16:00:53.025346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e253c65bf95'
down_revision = '0de38857bfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('patient_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['payment_received_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('patient_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
