"""Fix case transfer schema

Revision ID: 4eaf7dcc0327
Revises: 1da1d476518e
Create Date: 2025-01-25 21:25:41.658278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eaf7dcc0327'
down_revision = '1da1d476518e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_attachments')
    op.drop_table('cases')
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('closing_notes')

    with op.batch_alter_table('case_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_constraint('case_history_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctor', ['doctor_id'], ['id'])
        batch_op.drop_column('action')
        batch_op.drop_column('user_id')
        batch_op.drop_column('details')

    with op.batch_alter_table('case_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('transfer_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transfer_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patient_condition', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patient_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_medications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transfer_priority', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['patient_id'], ['id'])
        batch_op.drop_column('transfer_date')
        batch_op.drop_column('notes')
        batch_op.drop_column('reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('transfer_date', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('transfer_priority')
        batch_op.drop_column('current_medications')
        batch_op.drop_column('patient_history')
        batch_op.drop_column('patient_condition')
        batch_op.drop_column('transfer_notes')
        batch_op.drop_column('transfer_reason')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('case_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('action', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('case_history_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('notes')
        batch_op.drop_column('doctor_id')

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closing_notes', mysql.TEXT(), nullable=True))

    op.create_table('cases',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('diagnosis', mysql.TEXT(), nullable=True),
    sa.Column('treatment', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('show_to_patient', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('closing_notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='cases_ibfk_1'),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name='cases_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('case_attachments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('case_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('file_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.Column('uploaded_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='case_attachments_ibfk_1'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], name='case_attachments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
