"""Fix case attachments foreign key

Revision ID: a6e614f1f62f
Revises: case_history_update_1
Create Date: 2025-01-25 12:11:02.843723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6e614f1f62f'
down_revision = 'case_history_update_1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('case_transfer_logs')
    op.drop_table('case')
    op.drop_table('case_attachment')
    with op.batch_alter_table('case_history', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_constraint('case_history_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'cases', ['case_id'], ['id'])

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('closing_notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closing_notes', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('case_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('case_history_ibfk_1', 'case', ['case_id'], ['id'])
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    op.create_table('case_attachment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('case_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('file_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.Column('uploaded_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name='case_attachment_ibfk_1'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], name='case_attachment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('case',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('diagnosis', mysql.TEXT(), nullable=True),
    sa.Column('treatment', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('show_to_patient', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('closing_notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='case_ibfk_2'),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name='case_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('case_transfer_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('case_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('from_doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('to_doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='case_transfer_logs_ibfk_1'),
    sa.ForeignKeyConstraint(['from_doctor_id'], ['doctor.id'], name='case_transfer_logs_ibfk_2'),
    sa.ForeignKeyConstraint(['to_doctor_id'], ['doctor.id'], name='case_transfer_logs_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('case_attachments')
    # ### end Alembic commands ###
