"""Add patient details to case transfer

Revision ID: add_patient_to_case_transfer
Revises: update_case_transfer_fields
Create Date: 2025-01-25 20:45:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_patient_to_case_transfer'
down_revision = 'update_case_transfer_fields'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_transfer', schema=None) as batch_op:
        # Add patient_id column
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        # Add foreign key constraint
        batch_op.create_foreign_key('fk_case_transfer_patient', 'user', ['patient_id'], ['id'])
        # Add patient details columns
        batch_op.add_column(sa.Column('patient_condition', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patient_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_medications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('transfer_priority', sa.String(20), nullable=True))  # urgent, normal, low

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_transfer', schema=None) as batch_op:
        # Remove patient details columns
        batch_op.drop_column('transfer_priority')
        batch_op.drop_column('current_medications')
        batch_op.drop_column('patient_history')
        batch_op.drop_column('patient_condition')
        # Remove foreign key constraint and column
        batch_op.drop_constraint('fk_case_transfer_patient', type_='foreignkey')
        batch_op.drop_column('patient_id') 