"""Add patient details fields to User model

Revision ID: d6ef9f69b376
Revises: 4eaf7dcc0327
Create Date: 2025-01-26 01:04:49.017338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ef9f69b376'
down_revision = '4eaf7dcc0327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('aadhar_number', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('patient_number', sa.String(length=11), nullable=True))
        batch_op.create_unique_constraint(None, ['patient_number'])
        batch_op.create_unique_constraint(None, ['aadhar_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('patient_number')
        batch_op.drop_column('aadhar_number')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
