"""Add payment fields

Revision ID: f31c1ef42263
Revises: 31a014470bc3
Create Date: 2025-05-28 17:40:03.581686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f31c1ef42263'
down_revision = '31a014470bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('pin_code',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('patient_number',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index('aadhar_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('aadhar_number', ['aadhar_number'], unique=True)
        batch_op.alter_column('patient_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.alter_column('pin_code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###
