"""Update case transfer fields

Revision ID: update_case_transfer_fields
Revises: 618060c750ef
Create Date: 2025-01-25 20:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'update_case_transfer_fields'
down_revision = '618060c750ef'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_transfer', schema=None) as batch_op:
        # Rename columns
        batch_op.alter_column('reason', new_column_name='transfer_reason')
        batch_op.alter_column('notes', new_column_name='transfer_notes')
        batch_op.alter_column('transfer_date', new_column_name='created_at')
        
        # Add new columns
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_transfer', schema=None) as batch_op:
        # Revert column names
        batch_op.alter_column('transfer_reason', new_column_name='reason')
        batch_op.alter_column('transfer_notes', new_column_name='notes')
        batch_op.alter_column('created_at', new_column_name='transfer_date')
        
        # Remove added columns
        batch_op.drop_column('updated_at') 